spring:
  application:
    name: config-server

  profiles:
    active: git, vault

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DevSecOps-Microservices/config-repo.git
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          clone-on-start: true
          search-paths: "."
        vault:
          host: ${VAULT_ADDR}
          port: ${VAULT_PORT:443}
          scheme: https
          authentication: TOKEN
          token: ${VAULT_TOKEN}
          kv-version: 2
          backend: secret
          default-key: app

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics

  endpoint:
    health:
      config:
        enabled: false

  metrics:
    tags:
      application: ${spring.application.name}